#!/usr/bin/env php
<?php
namespace think;
// 命令行入口文件
// 加载基础文件
require __DIR__ . '/vendor/autoload.php';
define('IDCSMART_ROOT', __DIR__ . '/');
define('WEB_ROOT', __DIR__ . '/public/');
define('UPLOAD_DEFAULT', __DIR__ . '/public/upload/common/default/');

// 应用初始化
(new App())->console->run();